### PR TITLE
Made it no longer run as root and added a way to save your secret

### PR DESCRIPTION
**Pull request by kevinf100**

### CODE REVIEW

**Comment by PepaonDrugs** [comment]
Hey,

The Dockerfile looks great, but can you tell me what the secret volume is used for? It doesn't seem to be used by Playit.

**Comment by kevinf100** [comment]
I created a symlink from /etc/playit to the volume. The secret file is for how the tunnel connects to playit
________________________________

**Comment by PepaonDrugs** [comment]
Yes, I get that you created a symlink, but when I use it, it saves the playit secret in playit.toml, which is saved in the /app folder.

**Comment by kevinf100** [comment]
What I saw is playit first checks next to the executable location for a secret. It than check /etc/playit and saves it to /etc/playit when it makes one. I'll double check when I get home, but this is what happened to me from an empty /app
________________________________

**Comment by PepaonDrugs** [comment]
Okay, it's actually saved under /root/.config/playit_gg. They changed it in this version. I will update it.

**Comment by kevinf100** [comment]
I just looked at the code. It looks like it depends on the Linux version. https://github.com/playit-cloud/playit-agent/blob/master/packages/agent_cli/src/playit_secret.rs#L38
I can fully unwrap how this works later. But normally /root is the home of rott
________________________________

**Comment by PepaonDrugs** [comment]
Just updated the symlink to the /app volume, works great now.

**Comment by kevinf100** [comment]
My idea on not doing that is so you could have multiple secret keys and one app folder for the program itself. No idea if people who ever do that tho
________________________________

**Comment by PepaonDrugs** [comment]
Oh, okay, that could be a thing. I will change it tomorrow and then merge it.

**Comment by kevinf100** [comment]
Looking at some Rust info, `dirs::config_local_dir()` is `$XDG_CONFIG_HOME or $HOME/.config`  
Depending on your Linux version this could be `/etc` or `/home/user`. This is why you had it `/root`, because whatever OS you tired it on was newer/different than the container's OS and `/root` is the user 0/root home. https://docs.rs/dirs/latest/dirs/fn.config_dir.html

**Comment by PepaonDrugs** [comment]
Oh yeah, that makes sense. By the way, I think I will change it so that the playit volume just saves the secret, not the binary. This way, you can use multiple secrets and don't need to use more than one volume

**Comment by kevinf100** [comment]
You don't need to use two volumes if you don't want to now. In the cli or compose you can just exclude volume(s) and it'll work just fine. Also, do you want me to switch the startup to run a script/sh instead of the binary? This way we can allow people to pass flags/args to the program. This can also allow people to run it as root if they really want to.
________________________________

**Comment by PepaonDrugs** [comment]
Yes, I think it should only take one volume. Also, I just changed the Dockerfile so that it starts from /secret. This way, only the secret is saved in /secret where the volume is mapped. I also thought of making it run with a script, but I decided against it. If they want to pass arguments or flags, they can do this directly via Docker

**Pull request merged**
